<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Catalog\Block\Product\AbstractProduct;
use Magento\Catalog\ViewModel\Product\Listing\PreparePostData;
use Magento\Framework\App\ActionInterface;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

/* @var $block AbstractProduct */
/** @var SecureHtmlRenderer $secureRenderer */
?>

<?php
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int)$block->isShuffled();
            $isWeightedRandom = (int)$block->getRotation()->isWeightedRandom($block->getProductListType());
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = false;
            $showCart = false;
            $templateType = true;
            $description = false;
        }
        break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $isWeightedRandom = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = false;
            $showCart = true;
            $templateType = true;
            $description = false;
        }
        break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int)$block->isShuffled();
            $isWeightedRandom = (int)$block->getRotation()->isWeightedRandom($block->getProductListType());

            $showAddTo = false;
            $showCart = true;
            $templateType = true;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;
            $isWeightedRandom = 0;

            $showAddTo = false;
            $showCart = false;
            $templateType = true;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    default:
        $exist = null;
}

$_item = null;
?>

<?php if ($exist): ?>

<?php if ($type == 'related' || $type == 'upsell'): ?>

<div class="block <?= $escaper->escapeHtmlAttr($class) ?>"
    <?php if ($type == 'related'): ?>
        data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}'
    <?php else: ?>
        data-mage-init='{"upsellProducts":{}}'
    <?php endif; ?>
     data-limit="<?= $escaper->escapeHtmlAttr($limit) ?>"
     data-shuffle="<?= /* @noEscape */
     $shuffle ?>"
     data-shuffle-weighted="<?= /* @noEscape */
     $isWeightedRandom ?>">

    <?php else: ?>
    <div class="block <?= $escaper->escapeHtmlAttr($class) ?>">
        <?php endif; ?>
        <div class="block-title title">
            <strong id="block-<?= $escaper->escapeHtmlAttr($class) ?>-heading" role="heading"
                    aria-level="2"><?= $escaper->escapeHtml($title) ?></strong>
        </div>
        <div class="block-content content" aria-labelledby="block-<?= $escaper->escapeHtmlAttr($class) ?>-heading">
            <div class="products wrapper grid products-grid products-<?= $escaper->escapeHtmlAttr($type) ?>">
                <ol class="products list items product-items">
                    <?php foreach ($items as $_item): ?>
                        <?php $available = ''; ?>
                        <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                            <?php if (!$_item->getRequiredOptions()): ?>
                                <?php $available = 'related-available'; ?>
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php if ($type == 'related' || $type == 'upsell'): ?>
                            <li class="item product product-item"
                            id="product-item_<?= /* @noEscape */
                            $_item->getId() ?>"
                            data-shuffle-group="<?= $escaper->escapeHtmlAttr($_item->getPriority()) ?>" >
                            <?= /* @noEscape */
                            $secureRenderer->renderStyleAsTag(
                                'display:none;',
                                'li#product-item_' . $_item->getId()
                            ) ?>
                        <?php else: ?>
                            <li class="item product product-item">
                        <?php endif; ?>

                        <div class="product-item-info <?= $available ?>">
                            <div class="info-left">
                                <a href="<?= $escaper->escapeUrl($block->getProductUrl($_item)) ?>"
                                   class="product photo product-item-photo">
                                    <?= $block->getImage($_item, $image)->toHtml() ?>
                                </a>
                                <div class="product details product-item-details">
                                    <strong class="product name product-item-name"><a
                                            class="product-item-link"
                                            title="<?= $escaper->escapeHtmlAttr($_item->getName()) ?>"
                                            href="<?= $escaper->escapeUrl($block->getProductUrl($_item)) ?>">
                                            <?= $escaper->escapeHtml($_item->getName()) ?></a>
                                    </strong>

                                    <?php if ($templateType): ?>
                                        <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                    <?php endif; ?>

                                    <?= $block->getProductPrice($_item) ?>

                                    <?php if ($showAddTo || $showCart): ?>
                                        <?php // phpcs:disable?>
                                        <div class="product actions product-item-actions">
                                            <?php if ($showCart): ?>
                                                <div class="actions-primary">
                                                    <?php if ($_item->isSaleable()): ?>
                                                        <?php if (!$_item->getTypeInstance()->isPossibleBuyFromList($_item)): ?>
                                                            <button
                                                                class="action tocart primary"
                                                                data-mage-init='{"redirectUrl": {"url": "<?= $escaper->escapeUrl($block->getAddToCartUrl($_item)) ?>"}}'
                                                                type="button"
                                                                title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>">
                                                                <span><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
                                                            </button>
                                                        <?php else : ?>
                                                            <?php
                                                            /** @var $viewModel PreparePostData */
                                                            $viewModel = $block->getViewModel();
                                                            $postArray = $viewModel->getPostData(
                                                                $escaper->escapeUrl($block->getAddToCartUrl($_item)),
                                                                ['product' => $_item->getEntityId()]
                                                            );
                                                            $value = $postArray['data'][ActionInterface::PARAM_NAME_URL_ENCODED];
                                                            ?>
                                                            <form data-role="tocart-form"
                                                                  data-product-sku="<?= $escaper->escapeHtmlAttr($_item->getSku()) ?>"
                                                                  action="<?= $escaper->escapeUrl($block->getAddToCartUrl($_item)) ?>"
                                                                  method="post">
                                                                <input type="hidden" name="product"
                                                                       value="<?= /* @noEscape */
                                                                       (int)$_item->getEntityId() ?>">
                                                                <input type="hidden"
                                                                       name="<?= /* @noEscape */
                                                                       ActionInterface::PARAM_NAME_URL_ENCODED ?>"
                                                                       value="<?= /* @noEscape */
                                                                       $value ?>">
                                                                <?= $block->getBlockHtml('formkey') ?>
                                                                <button type="submit"
                                                                        title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                                        class="action tocart primary">
                                                                    <span><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
                                                                </button>
                                                            </form>
                                                        <?php endif; ?>
                                                    <?php else: ?>
                                                        <?php if ($_item->isAvailable()): ?>
                                                            <div class="stock available">
                                                                <span><?= $escaper->escapeHtml(__('In stock')) ?></span>
                                                            </div>
                                                        <?php else: ?>
                                                            <div class="stock unavailable">
                                                                <span><?= $escaper->escapeHtml(__('Out of stock')) ?></span>
                                                            </div>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>

                                            <?php if ($showAddTo): ?>
                                                <div class="secondary-addto-links actions-secondary"
                                                     data-role="add-to-links">
                                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                                        <?= $addToBlock->setProduct($_item)->getChildHtml() ?>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                        <?php // phpcs:enable?>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <!--                                view product button for upsell-->
                            <?php if ($type == 'upsell'): ?>
                                <a
                                    class="product-view-product"
                                    title="<?= $escaper->escapeHtmlAttr($_item->getName()) ?>"
                                    href="<?= $escaper->escapeUrl($block->getProductUrl($_item)) ?>">
                                    View Product
                                </a>
                            <?php endif; ?>

                        </div>
                        </li>
                    <?php endforeach ?>
                </ol>
            </div>
        </div>
    </div>
    <?php if (!$block->isRedirectToCartEnabled() && $_item): ?>
        <script type="text/x-magento-init">
            {
                "[data-role=tocart-form], .form.map.checkout": {
                    "catalogAddToCart": {
                        "product_sku": "<?= $escaper->escapeJs($_item->getSku()) ?>"
                    }
                }
            }
        </script>

    <?php endif; ?>

    <?php if ($templateType): ?>
        <script>
            require(['jquery'], function ($) {
                "use strict";

                $('.rating-summary').ready(function() {
                    const reviewLinks = [...document.querySelector('.reviews-actions').getElementsByTagName('a')];
                    const reviewSection = document.querySelector('.product.info.detailed');
                    const reviewTab = document.getElementById('tab-label-reviews');

                    reviewLinks.forEach(link => {
                        link.addEventListener('click', () => {
                            showElement(reviewSection);
                        });
                    })

                    reviewTab.addEventListener('click', () => {
                        hideElement(reviewSection);
                    });

                    function showElement(el){
                        el.style.display = 'block';
                    }

                    function hideElement(el){
                        el.style.display = 'none';
                    }
                });

            });
        </script>
    <?php endif; ?>

    <?php endif; ?>
